hamlet/urls.py
from django.urls import path
from . import views

app_name = 'hamlet'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('moora_project_list/', views.moora_project_list, name='moora_project_list'),
    path('A_name_list/', views.A_name_list, name='A_name_list'),
    path('A1_easy_name/', views.A1_easy_name, name='A1_easy_name'),
    path('result_A1/', views.result_A1, name='result_A1'),
    path('A2_global_name/', views.A2_global_name, name='A2_global_name'),
    path('result_A2/', views.result_A2, name='result_A2'),
    path('A3_pure_name/', views.A3_pure_name, name='A3_pure_name'),
    path('result_A3/', views.result_A3, name='result_A3'),
    path('A4_popular_name/', views.A4_popular_name, name='A4_popular_name'),
    path('result_A4/', views.result_A4, name='result_A4'),
    path('A5_fetus_name/', views.A5_fetus_name, name='A5_fetus_name'),
    path('A5_1_pure_fetus_name/', views.A5_1_pure_fetus_name, name='A5_1_pure_fetus_name'),
    path('result_A5/', views.result_A5, name='result_A5'),
    path('A5_2_well_hearded_fetus_name/', views.A5_2_well_hearded_fetus_name, name='A5_2_well_hearded_fetus_name'),
    path('result_A52/', views.result_A52, name='result_A52'),
    path('B_nick_name_list/', views.B_nick_name_list, name='B_nick_name_list'),
    path('B1_random_nick_name/', views.B1_random_nick_name, name='B1_random_nick_name'),
    path('result_B1/', views.result_B1, name='result_B1'),
    path('B2_novel_nick_name/', views.B2_novel_nick_name, name='B2_novel_nick_name'),
    path('result_B2/', views.result_B2, name='result_B2'),
    path('C_others_list/', views.C_others_list, name='C_others_list'),
    path('C1_random/', views.C1_random, name='C1_random'),
    path('C1_random_2/', views.C1_random_2, name='C1_random_2'),
    path('result_C1/', views.result_C1, name='result_C1'),
    path('C2_lotto/', views.C2_lotto, name='C2_lotto'),
    path('C2_1_random_lotto/', views.C2_1_random_lotto, name='C2_1_random_lotto'),
    path('C2_lotto2/', views.C2_lotto2, name='C2_lotto2'),
    path('C2_2_unit_lotto/', views.C2_2_unit_lotto, name='C2_2_unit_lotto'),
    path('result_C2/', views.result_C2, name='result_C2'),
    path('result_C22/', views.result_C22, name='result_C22'),

]

mooramoora/urls.py
from django.contrib import admin
from django.urls import path, include
from hamlet import views

urlpatterns = [
    path('', views.index),
    path('hamlet/', include('hamlet.urls')),
    path('admin/', admin.site.urls),
]

hamlet/models.py
from django.db import models

# Create your models here.

hamlet/views.py
from django.shortcuts import render
from datetime import date  # 글로벌 모듈 임폴트
import random #진짜 랜덤 임포트
import hgtk # 한글 자모음



def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


def moora_project_list(request):
    return render(request, 'moora_project_list.html')


def A_name_list(request):
    return render(request, 'A_name_list.html')


def A1_easy_name(request):
    return render(request, 'A1_easy_name.html')

def result_A1(request):  # 무지 추가
    bday = request.GET.get('bday')
    easy_name = ['려진', '린동', '나찬', '동운', '인찬', '진송', '해니', '강군', '종보', '진민', '나강', '수찬', '해안', '산동', '운민', '찬단', '나찬', '동훈', '홍니',
                 '산여', '훈군', '기보', '나진', '수란', '찬단', '민나', '기강', '한보', '모동', '린찬', '기모', '수저', '빈운', '군강', '군모', '산니', '론단', '찬단',
                 '려진', '어빈', '세래', '민린', '빈해', '인단', '빈모', '어종', '찬찬', '빈군', '단운', '모운', '군훈', '니모', '동나', '해군', '서찬', '동찬', '론찬',
                 '린래', '운단', '니단', '단휘', '기여', '종기', '단홍', '휘자', '운래', '여군', '민강', '동동', '빈군', '안훈', '모기', '모단', '빈민', '휘운', '여보',
                 '찬한', '한종', '군신', '동모', '어단', '단찬', '래란', '민안', '휘찬', '모루', '나찬', '찬니', '단린', '찬민', '군진', '동모', '찬종', '해기', '운보',
                 '안찬', '보여', '해기', '래모', '보찬', '해니', '기군', '찬빈', '인종', '빈어', '해모', '빈모', '모빈', '나수', '보보', '모안', '산수', '저안', '찬모',
                 '한준', '모신', '홍란', '기니', '군안', '빈나', '보기', '빈단', '려기', '찬니', '보보', '해종', '찬신', '래려', '민기', '니홍', '훈찬', '찬루', '여자',
                 '여나', '운나', '빈빈', '니기', '군찬', '려산', '준니', '운모', '온찬', '종단', '단나', '단찬', '찬니', '홍빈', '민니', '강해', '보빈', '니휘', '빈니',
                 '니모', '나찬', '동기', '니민', '해안', '운온', '자나', '준단', '군린', '인단', '민동', '니준', '종준', '훈산', '한어', '니단', '린모', '려운', '종보',
                 '찬려', '나란', '민니', '찬보', '보린', '민휘', '여신', '보려', '단찬', '기단', '나강', '기군', '온려', '홍세', '니나', '홍세', '보민', '단나', '보보',
                 '니홍', '니단', '준란', '인민', '빈민', '한군', '기빈', '단자', '니강', '래해', '래훈', '보재', '빈동', '준니', '동니', '나찬', '동니', '민루', '세려',
                 '종민', '운니', '민나', '빈모', '서동', '니군', '훈모', '빈홍', '강인', '산나', '한니', '해보', '군안', '보강', '훈해', '나휘', '민래', '여빈', '린민',
                 '빈휘', '종홍', '기준', '인강', '한안', '빈안', '군니', '수빈', '나단', '단보', '니단', '찬론', '홍동', '저찬', '훈자', '빈준', '려찬', '자휘', '산모',
                 '수진', '민빈', '세빈', '단래', '운니', '민란', '니홍', '보찬', '니준', '빈란', '래홍', '빈단', '안모', '강니', '려홍', '진훈', '훈세', '빈세', '종저',
                 '단훈', '기기', '나기', '니서', '려준', '찬니', '찬진', '안저', '훈모', '한기', '민저', '민자', '동민', '루자', '여종', '동민', '진신', '니준', '단단',
                 '단민', '찬민', '빈신', '나자', '모보', '홍찬', '기빈', '보찬', '기모', '모나', '운찬', '단찬', '니모', '홍단', '진루', '보찬', '모수', '재한', '기저',
                 '운수', '민찬', '송찬', '준휘', '어종', '찬니', '종찬', '모기', '루강', '기론', '인동', '동찬', '민란', '재군', '찬종', '진빈', '신온', '려찬', '저니',
                 '찬해', '나단', '온온', '나휘', '빈동', '찬단', '운휘', '보나', '빈온', '빈수', '민루', '린니', '단찬', '자기', '수군', '모강', '단군', '인단', '어온',
                 '나민', '모모', '자온', '래단', '모홍', '여찬', '모군', '찬려', '찬민', '강산', '려빈', '동저', '단해', '찬루', '단산', '송찬', '인기', '기빈', '나여',
                 '기운', '빈산', '니모', '휘훈']
    month = bday[5:7]
    day = bday[8:]
    d0 = date(2019, 1, 1)
    d1 = date(2019, int(month), int(day))  # 날짜 저장.
    delta = d1 - d0
    result = easy_name[delta.days]
    context = { 'name': result}
    return render(request, 'result_A1.html', context)


def A2_global_name(request):
    return render(request, 'A2_global_name.html')

def result_A2(request):  # 무지 추가
    bday = request.GET.get('bday')
    sex = request.GET.get('sex')

    global_popular_m_name = ['비한', '에런', '이안', '테오', '다니엘', '라일리', '다니엘', '레오', '로건', '로건',
                             '해리', '해리', '레오', '테오', '로건', '단테', '다니엘', '이반', '시온', '리오',
                             '시온', '다니엘', '해리', '리오', '라일리', '이든', '이반', '이안', '노아', '노아',
                             '다니엘', '라일리', '해리', '시온', '아서', '이든', '리오', '아서', '이든', '테오',
                             '로건', '테오', '이안', '리오', '에단', '이안', '단테', '이안', '테오', '에단', '조엘',
                             '로건', '비한', '다니엘', '에런', '이든', '노아', '이든', '조엘', '라일리', '하디',
                             '테오', '테오', '단테', '이안', '다니엘', '에런', '해리', '로건', '시온', '비한',
                             '단테', '하디', '비한', '해리', '단테', '다니엘', '비한', '해리', '로건', '에단',
                             '에런', '리오', '에런', '노아', '하디', '테오', '노아', '레오', '이든', '테오', '하디',
                             '로건', '로건', '이든', '아서', '리오', '비한', '아서', '테오', '레오', '에단', '이안',
                             '다니엘', '라일리', '아서', '아서', '아서', '비한', '해리', '라일리', '해리', '리오',
                             '아서', '레오', '이든', '해리', '단테', '조엘', '라일리', '해리', '하디', '라일리',
                             '이든', '시온', '리오', '이든', '로건', '에런', '이반', '해리', '라일리', '하디', '조엘',
                             '에단', '에단', '노아', '레오', '로건', '로건', '해리', '테오', '이안', '테오', '테오',
                             '리오', '라일리', '조엘', '시온', '이든', '리오', '레오', '이반', '이든', '이든', '이든',
                             '테오', '리오', '리오', '에단', '비한', '시온', '라일리', '이반', '에런', '이든',
                             '다니엘', '라일리', '비한', '로건', '이든', '조엘', '단테', '레오', '이든', '로건', '에런',
                             '비한', '로건', '다니엘', '단테', '이든', '이든', '에런', '에런', '이든', '레오', '로건',
                             '라일리', '시온', '다니엘', '비한', '시온', '시온', '리오', '이안', '시온', '이안', '이반',
                             '아서', '해리', '시온', '리오', '테오', '아서', '이반', '이든', '하디', '테오', '아서',
                             '에단', '에런', '레오', '라일리', '이반', '비한', '조엘', '이든', '노아', '단테', '시온',
                             '라일리', '해리', '아서', '로건', '이든', '리오', '시온', '비한', '리오', '하디', '조엘',
                             '에런', '테오', '단테', '테오', '라일리', '이안', '하디', '아서', '에단', '로건', '해리',
                             '테오', '다니엘', '다니엘', '하디', '에런', '이든', '테오', '해리', '레오', '라일리', '하디',
                             '이든', '조엘', '테오', '노아', '테오', '이든', '해리', '테오', '라일리', '다니엘', '이안',
                             '레오', '이든', '에단', '로건', '이든', '로건', '해리', '비한', '에런', '다니엘', '테오',
                             '테오', '테오', '에단', '레오', '테오', '에런', '이안', '에단', '아서', '레오', '하디',
                             '이든', '이든', '노아', '에런', '에단', '노아', '해리', '레오', '이든', '다니엘', '조엘',
                             '아서', '해리', '시온', '조엘', '해리', '다니엘', '테오', '아서', '단테', '에런', '로건',
                             '레오', '시온', '시온', '시온', '단테', '에런', '시온', '로건', '이반', '테오', '테오',
                             '로건', '시온', '단테', '해리', '시온', '이안', '라일리', '라일리', '비한', '조엘', '이반',
                             '리오', '단테', '이안', '에런', '레오', '아서', '해리', '다니엘', '에단', '에런', '리오',
                             '에런', '하디', '에런', '레오', '에단', '시온', '로건', '이안', '단테', '이반', '하디',
                             '비한', '리오', '비한', '해리', '테오', '이안', '이안', '리오', '라일리', '노아', '테오',
                             '라일리']
    global_popular_fm_name = ['쥬리', '사라', '모건', '지안', '지안', '지안', '쥬리', '쥬리', '모건', '아린', '일라',
                              '모건', '다나', '엘라', '사라', '나나', '나나', '지안', '해리', '리나', '지아', '엘라',
                              '한나', '아론', '다나', '지안', '해리', '쥬리', '제나', '하니', '아론', '해리', '제나',
                              '리나', '모건', '나나', '쥬리', '다나', '다나', '리나', '일라', '모건', '노라', '일라',
                              '지나', '제나', '리나', '테사', '제나', '일라', '엘라', '이비', '나나', '지나', '제나',
                              '이젤', '지안', '리나', '노라', '한나', '이젤', '이젤', '지아', '이젤', '아론', '하니',
                              '일라', '아론', '사라', '지나', '루미', '한나', '쥬리', '한나', '노라', '이젤', '나나',
                              '나나', '쥬리', '한나', '아린', '일라', '제나', '아린', '리나', '다나', '지안', '지나',
                              '이비', '하니', '제나', '아론', '이젤', '조이', '조이', '이비', '테사', '하니', '아론',
                              '아론', '사라', '모건', '한나', '해리', '제나', '조이', '지아', '한나', '제나', '다나',
                              '하니', '아론', '이젤', '한나', '사라', '제나', '이젤', '조이', '지나', '사라', '지아',
                              '이젤', '일라', '엘라', '다나', '나나', '아린', '조이', '루미', '사라', '엘라', '지안',
                              '이비', '아론', '노라', '지아', '한나', '하니', '일라', '지아', '이비', '지안', '일라',
                              '모건', '한나', '지나', '일라', '테사', '하니', '조이', '테사', '이젤', '일라', '일라',
                              '루미', '리나', '사라', '엘라', '조이', '테사', '다나', '노라', '리나', '해리', '루미',
                              '쥬리', '한나', '제나', '지안', '아론', '나나', '노라', '하니', '지안', '노라', '하니',
                              '지아', '리나', '한나', '나나', '지안', '쥬리', '해리', '해리', '나나', '리나', '조이',
                              '지나', '이젤', '모건', '리나', '한나', '루미', '엘라', '아론', '해리', '엘라', '한나',
                              '쥬리', '테사', '지나', '다나', '지안', '해리', '제나', '다나', '이젤', '지아', '사라',
                              '이비', '리나', '나나', '지아', '다나', '아론', '제나', '나나', '해리', '엘라', '리나',
                              '지아', '쥬리', '사라', '조이', '엘라', '지나', '쥬리', '이비', '루미', '하니', '루미',
                              '다나', '지나', '지아', '지아', '나나', '지안', '하니', '아린', '지안', '모건', '일라',
                              '이젤', '테사', '엘라', '다나', '테사', '사라', '조이', '노라', '하니', '하니', '한나',
                              '이젤', '이젤', '일라', '아론', '사라', '리나', '해리', '지아', '이젤', '지나', '테사',
                              '지안', '나나', '이비', '한나', '아린', '엘라', '지아', '사라', '리나', '하니', '하니',
                              '사라', '지나', '모건', '사라', '일라', '이젤', '엘라', '루미', '다나', '하니', '지아',
                              '지안', '아린', '아린', '하니', '사라', '쥬리', '이젤', '이젤', '모건', '지나', '하니',
                              '아린', '리나', '지안', '조이', '하니', '아린', '엘라', '지안', '쥬리', '아론', '지나',
                              '지안', '일라', '쥬리', '일라', '쥬리', '쥬리', '일라', '지아', '아린', '이젤', '리나',
                              '모건', '테사', '다나', '테사', '사라', '엘라', '모건', '한나', '일라', '지나', '리나',
                              '이비', '제나', '제나', '지아', '조이', '지안', '아론', '제나', '엘라', '지아', '노라',
                              '리나', '제나', '모건', '일라', '이비', '제나', '지나', '리나', '쥬리', '지안', '리나',

hamlet/templates/A3_pure_name.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">
            <form action="{% url 'hamlet:result_A3' %}" method="get" align="center">
                <!--        # 이 경로를 통해서 views.result_A1이 실행되도록 함.-->
                <h1>순우리말 이름</h1><br><br>
                <h3> 성별을 입력하세요. </h3>
                <input type="radio" name="sex" value="0" required>여성
                <input type="radio" name="sex" value="1" required>남성<br><br>
                <h3> 생일을 입력하세요. </h3>
                <input type="date" name="bday" required>
                <!--        # 날짜 값을 입력 받음-->
                <input class="btn btn-link ml-3 text-white bg-secondary" type="submit" value="결과보기">
                <!--        # 제출 버튼-->
            </form>
        </section>
    </div>
{% endblock %}

hamlet/templates/A4_popular_name.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">
            <form action="{% url 'hamlet:result_A4' %}" method="get" align="center">
            <h1>인기있는 이름</h1><br><br>
            <h3> 성별을 입력하세요. </h3>
            <input type="radio" name="sex" value="0" required>여성
            <input type="radio" name="sex" value="1" required>남성<br><br>
            <h3> 생일을 입력하세요. </h3>
            <input type="date" name="bday" required>
            <!--        # 날짜 값을 입력 받음-->
            <input class="btn btn-link ml-3 text-white bg-secondary" type="submit" value="결과보기">
            <!--        # 제출 버튼-->
            </form>
        </section>
    </div>
{% endblock %}

hamlet/templates/A5_1_pure_fetus_name.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">
            <form action="{% url 'hamlet:result_A5' %}" method="get" align="center">
                <h1>순우리말 태명</h1><br><br>
                <h3> 생일을 입력하세요. </h3><br>
                <!--        # 이 경로를 통해서 views.result_A1이 실행되도록 함.-->
                <input type="date" name="bday" required>
                <!--        # 날짜 값을 입력 받음-->
                <input class="btn btn-link ml-3 text-white bg-secondary" type="submit" value="결과보기">
                <!--        # 제출 버튼-->
            </form>
        </section>
    </div>
{% endblock %}

hamlet/templates/B2_novel_nick_name.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">
            <h1 align="center">인디언식 닉네임</h1><br><br>
            <h3 align="center"> 생일을 입력하세요. </h3>
            <div class="form">
                <form action="{% url 'hamlet:result_B2' %}" method="get"><br>
                    <!--        # 이 경로를 통해서 views.result_A1이 실행되도록 함.-->
                    <input type="date" name="bday" required/>
                    <!--        # 날짜 값을 입력 받음-->

                    <input class="btn btn-link ml-3 text-white bg-secondary" type="submit" value="결과보기" style="background-color: white"/>
                    <!--        # 제출 버튼-->
                </form>
            </div>
        </section>
    </div>
{% endblock %}

hamlet/templates/C2_lotto2.html
{% extends 'base.html' %}
{% block body %}
<form action=" {% url 'hamlet:result_C22' %}" method="get">
        <h2>번호 입력</h2>
        "1번대 로또 번호를 몇 개 원하십니까?"
        <input type="number" name="input_num_1" />
        "10번대 로또 번호를 몇 개 원하십니까?"
        <input type="number" name="input_num_10" />
        "20번대 로또 번호를 몇 개 원하십니까?"
        <input type="number" name="input_num_20" />
        "30번대 로또 번호를 몇 개 원하십니까?"
        <input type="number" name="input_num_30" />
        "40번대 로또 번호를 몇 개 원하십니까?"
        <input type="number" name="input_num_40" />


    <input type="submit" value="결과보기">
<!--        # 제출 버튼-->

{% endblock %}

hamlet/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


  <!-- About -->
 <section class="content-section" id="portfolio">
        <div class="container">
            <div class="content-section-heading text-center">
{#                <h2 class="mb-5">Other things</h2><br><br><br><br>#}
            </div>
            <div class="row justify-content-center" >
                <div class="col-4">
{#                    <a class="portfolio-item" href="{% url 'hamlet:about' %}">#}
                    <a href="http://github.com/KimRanA"> <img class="img-fluid" src="{% static 'img/rana.jpg' %}" alt=""></a>
                        <br><br>
                        <h2>김란아</h2>
                        <h3>프로젝트 기획, 설계, 개발</h3>
                        <a href="mailto:triple3dimple@gmail.com"><h3>triple3dimple@gmail.com</h3></a>
{#                    <a class="portfolio-item" href="{% url 'hamlet:about' %}">#}
                </div>
                <div class="col-4">
                    <a href="http://github.com/Moo-Ji"> <img class="img-fluid" src="{% static 'img/mooji.jpg' %}" alt=""></a>
                        <br><br>
                        <h2>허무지</h2>
                        <h3>프로젝트 개발, 디버깅</h3>
                        <a href="mailto:mooji.hur@outlook.com"><h3>mooji.hur@outlook.com</h3></a>
                </div>
            </div>

      </div>
  </section>
{% endblock %}

hamlet/templates/moora_project_list.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    <section class="content-section" id="portfolio">
        <div class="container">
            <div class="content-section-heading text-center">
                <h3 class="text-secondary mb-0">Your name is Hamlet.</h3>
                <h2 class="mb-5">MOO-RA-MOO-RA'S Projects</h2><br>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <a class="portfolio-item" href="{% url 'hamlet:A_name_list' %}">
                        <img class="img-fluid" src="{% static 'img/name.jpg' %}" alt="">
                    </a>
                </div>

                <div class="col-lg-4">
                    <a class="portfolio-item" href="{% url 'hamlet:B_nick_name_list' %}">
                        <img class="img-fluid" src="{% static 'img/nick_name.jpg' %}" alt="">
                    </a>
                </div>
                <div class="col-lg-4">
                    <a class="portfolio-item" href="{% url 'hamlet:C_others_list' %}">
                        <img class="img-fluid" src="{% static 'img/other.jpg' %}" alt="">
                    </a>
                </div>
            </div>
            </div>
    
    </section>
{% endblock %}

<!-- Portfolio -->


<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

hamlet/templates/result_A1.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">
            <h3 align="center">발음하기 쉬운 이름은</h3><br><br>

            <h2 align="center"> {{ name }} </h2>


        </section>
    </div>
{% endblock %}

hamlet/templates/result_A52.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">
            <h3 align="center">잘 들리는 태명은</h3><br><br>
            <h2 align="center">{{ name }} </h2>
        </section>
    </div>
{% endblock %}

hamlet/templates/result_B1.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">
            <h3 align="center">랜덤 닉네임은</h3><br><br>
            <h2 align="center">{{ name }}</h2>
        </section>
    </div>
{% endblock %}

hamlet/templates/result_B2.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">
            <h3 align="center">인디언식 이름은</h3><br><br>

            <h2 align="center"> {{ year }} {{ month }}의 {{ day }}</h2>


        </section>
    </div>
{% endblock %}

hamlet/templates/result_C2.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <section class="birthday d-flex flex-column justify-content-center align-items-center">

            <form action="" method="get" align="center">
            <h1>Lotto</h1><br>
                {% for i in result %}
                    <h3>{{ i }} <br></h3>
                {% endfor %}
            </form>
        </section>
    </div>
{% endblock %}